<?php 
require_once('./fpdf184/fpdf.php');
$conn = mysqli_connect('localhost','root','','fees');
if(isset($_POST['btn_gen']))
{
    $class = $_GET['class'];
    $select = mysqli_query($conn," select * from student where class = '$class'order by  First_name asc");
    $balance = mysqli_fetch_assoc(mysqli_query($conn,"SELECT fees from admin"));
         
    $pdf = new FPDF(orientation:'P',unit : 'mm',size:'a4');
    $pdf->SetFont(family:'arial',style:'B',size:'9');
    $pdf->AddPage();
    $pdf->cell(w:'169',h:'5',txt:' Fees Pay App',border:'1',ln:'1',align:'C');
    $pdf->cell(w:'10',h:'5',txt:'No',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'35',h:'5',txt:'First Name',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'25',h:'5',txt:'Last Name',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'45',h:'5',txt:'Phone',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'18',h:'5',txt:'Payment',border:'1',ln:'0',align:'C');
    $pdf->cell(w:'18',h:'5',txt:'Amount Left',border:'1',ln:'0',align:'C');
    $pdf->cell(w:'35',h:'5',txt:'Class',border:'1',ln:'1',align:'C');
    $n=1;
    $pdf->SetFont(family:'arial',style:'b',size:'7');
    while($row = mysqli_fetch_assoc($select)){
    $pdf->cell(w:'10',h:'5',txt:$n,border:'1',ln:'0',align:'C');
    $pdf->cell(w:'35',h:'5',txt:$row['First_name'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'25',h:'5',txt:$row['Last_name'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'23',h:'5',txt:$row['phone'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'23',h:'5',txt:$row['phone1'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'18',h:'5',txt:$row['payment'],border:'1',ln:'0',align:'C');
    $pdf->cell(w:'35',h:'5',txt:$row['class'],border:'1',ln:'1',align:'L');
    
    $n++;
    $ans = mysqli_num_rows($select);
    
    
}
$amount = mysqli_fetch_assoc(mysqli_query($conn,"SELECT sum(payment) as amount from student where class = '$class'")); 
$bal =  $balance['fees'];
$curr = $bal * $ans;
$amount = $amount['amount'];
$pdf->cell(w:'45',h:'5',txt:"Amount Payed",border:'1',ln:'0',align:'L');
$pdf->cell(w:'48',h:'5',txt:$amount.".00 RWF" ,border:'1',ln:'0',align:'L');
$pdf->cell(w:'41',h:'5',txt:"Amount Remain",border:'1',ln:'0',align:'L');
$pdf->cell(w:'35',h:'5',txt: $curr.".00 RWF",border:'1',ln:'1',align:'L');
$pdf->cell(w:'169',h:'10',txt:"This report generated by Burser manager on now()",border:'0',ln:'1',align:'R');
    $pdf->Output();
}
if(isset($_POST['generator']))
{
    $select = mysqli_query($conn," select * from inactivestudent order by First_name asc");
    $balance = mysqli_fetch_assoc(mysqli_query($conn,"SELECT fees from admin"));
         
    $pdf = new FPDF(orientation:'P',unit : 'mm',size:'a4');
    $pdf->SetFont(family:'arial',style:'B',size:'9');
    $pdf->AddPage();
    $pdf->cell(w:'169',h:'5',txt:' Fees Pay App',border:'1',ln:'1',align:'C');
    $pdf->cell(w:'10',h:'5',txt:'No',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'30',h:'5',txt:'First Name',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'25',h:'5',txt:'Last Name',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'35',h:'5',txt:'Phone',border:'1',ln:'0',align:'L');
    $pdf->cell(w:'21',h:'5',txt:'Payment',border:'1',ln:'0',align:'C');
    $pdf->cell(w:'23',h:'5',txt:'Amount Left',border:'1',ln:'0',align:'C');
    $pdf->cell(w:'25',h:'5',txt:'Class',border:'1',ln:'1',align:'C');
    $n=1;
    $pdf->SetFont(family:'arial',style:'b',size:'7');
    while($row = mysqli_fetch_assoc($select)){
    $pdf->cell(w:'10',h:'5',txt:$n,border:'1',ln:'0',align:'C');
    $pdf->cell(w:'30',h:'5',txt:$row['First_name'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'25',h:'5',txt:$row['Last_name'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'35',h:'5',txt:$row['phone'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'21',h:'5',txt:$row['payment'],border:'1',ln:'0',align:'L');
    $pdf->cell(w:'23',h:'5',txt:$row['Amount_left'],border:'1',ln:'0',align:'C');
    $pdf->cell(w:'25',h:'5',txt:$row['class'],border:'1',ln:'1',align:'L');
    
    $n++;
    $ans = mysqli_num_rows($select);
    
    
}
$amount = mysqli_fetch_assoc(mysqli_query($conn,"SELECT sum(payment) as amount from inactivestudent")); 
$bal =  $balance['fees'];
$curr = $bal * $ans;
$amount = $amount['amount'];
$pdf->cell(w:'40',h:'5',txt:"Amount Payed",border:'1',ln:'0',align:'L');
$pdf->cell(w:'60',h:'5',txt:$amount.".00 RWF" ,border:'1',ln:'0',align:'R');
$pdf->cell(w:'21',h:'5',txt:"Amount Remain",border:'1',ln:'0',align:'L');
$pdf->cell(w:'48',h:'5',txt: $curr.".00 RWF",border:'1',ln:'1',align:'R');
$pdf->cell(w:'169',h:'10',txt:"This report generated by Burser manager on now()",border:'0',ln:'1',align:'R');
    $pdf->Output();
}

?>

	
